DROP TABLE DOMICILIOS IF EXISTS;
DROP TABLE PACIENTES IF EXISTS;
DROP TABLE ODONTOLOGOS IF EXISTS;

CREATE TABLE DOMICILIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CALLE VARCHAR(25) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR(25) NOT NULL,
PROVINCIA VARCHAR(25) NOT NULL
);

CREATE TABLE PACIENTES(
ID INT AUTO_INCREMENT PRIMARY KEY,
APELLIDO VARCHAR(25) NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
DNI VARCHAR(10) NOT NULL,
FECHA_INGRESO DATE NOT NULL,
ID_DOMICILIO INT NOT NULL);

CREATE TABLE ODONTOLOGOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NROMATRICULA INT NOT NULL,
NOMBRE VARCHAR(25),
APELLIDO VARCHAR(25)
);

INSERT INTO DOMICILIOS VALUES (DEFAULT, 'SIEMPRE VIVA',123,'CABA','BUENOS AIRES');

INSERT INTO PACIENTES VALUES (DEFAULT, 'PEREZ','JUAN','45566', '2024-07-15', 1);

INSERT INTO ODONTOLOGOS VALUES(DEFAULT, 234, 'MARTIN', 'GONZALEZ'),
(DEFAULT, 134, 'MALENA', 'VALDEZ'),
(DEFAULT, 214, 'MARCO', 'LORENZO');
